import "server-only";

export const ANALYSIS_MODEL = "gpt-5.6-terra";
export const ANALYSIS_DISCLAIMER =
  "This sentiment and political-framing assessment was generated by AI. It is probabilistic, may be incomplete or incorrect, and should not be treated as objective fact.";

export const DEFAULT_ANALYSIS_BATCH_SIZE = 5;
export const MAX_ANALYSIS_BATCH_SIZE = 20;
export const MAX_ANALYSIS_REQUEST_LIMIT = 500;
export const MAX_ANALYSIS_ARTICLE_SELECTION = 100;
export const MAX_ANALYSIS_REQUEST_BODY_LENGTH = 10_000;
export const MAX_ARTICLE_TEXT_LENGTH = 60_000;
export const MAX_LOADED_TERMS = 20;

const REQUIRED_SERVER_ENVIRONMENT = [
  "OPENAI_API_KEY",
  "NEXT_PUBLIC_SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY",
] as const;

export class AnalysisConfigurationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "AnalysisConfigurationError";
  }
}

export function assertAnalysisConfiguration(): void {
  const missing = REQUIRED_SERVER_ENVIRONMENT.filter((name) => !process.env[name]?.trim());

  if (missing.length > 0) {
    throw new AnalysisConfigurationError(
      `Missing required analysis environment variables: ${missing.join(", ")}.`,
    );
  }

  getAnalysisBatchSize();
}

export function getAnalysisBatchSize(): number {
  const configured = process.env.ANALYSIS_BATCH_SIZE?.trim();

  if (!configured) {
    return DEFAULT_ANALYSIS_BATCH_SIZE;
  }

  if (!/^\d+$/.test(configured)) {
    throw new AnalysisConfigurationError("ANALYSIS_BATCH_SIZE must be an integer.");
  }

  const value = Number(configured);
  if (value < 1 || value > MAX_ANALYSIS_BATCH_SIZE) {
    throw new AnalysisConfigurationError(
      `ANALYSIS_BATCH_SIZE must be between 1 and ${MAX_ANALYSIS_BATCH_SIZE}.`,
    );
  }

  return value;
}
