export const DEFAULT_ARTICLES_PER_SOURCE = 5;
export const MAX_ARTICLES_PER_SOURCE = 10;
export const MAX_SOURCE_SELECTION = 25;
export const MAX_HOMEPAGE_CANDIDATES = 80;
export const MAX_DETAIL_ATTEMPTS_PER_SOURCE = 30;
export const OXYLABS_TIMEOUT_MS = 170_000;
export const MAX_OXYLABS_RESPONSE_BYTES = 15 * 1024 * 1024;
export const MIN_USABLE_HTML_LENGTH = 500;

